feat: add supported language csharp (#73)

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -7,6 +7,10 @@ branding:
   color: 'red'
 
 inputs:
+  language:
+    description: 'language'
+    required: true
+    default: ${{ github.event.pull_request.head.repo.language }}
 
   src_path:
     description: 'Path of source code'
@@ -21,6 +25,13 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Check Variables
+      if: contains(fromJSON('["python", "csharp"]'), inputs.language) != true
+      run: |
+        echo "::error::Invalid language"
+        exit 1
+      shell: bash
+
     - name: Move to path of action
       run: |
         cd ${{ github.action_path }}
@@ -56,8 +67,9 @@ runs:
     - name: Search symbol
       run: |
         cd ${{ github.action_path }}
+        LANGUAGE="$(echo ${{ inputs.language }} | tr '[:upper:]' '[:lower:]')"
         echo 'symbols<<\n' >> $GITHUB_ENV
-        symbols="$(pipenv run semgrep --config=${{ env.local_action_path }}/src/semgrep.yml ${{ inputs.src_path }} -q --vim | awk -F ':' '{ print $6 }')"
+        symbols="$(pipenv run semgrep --config=${{ env.local_action_path }}/src/rules/$LANGUAGE.yml ${{ inputs.src_path }} -q --vim | awk -F ':' '{ print $6 }')"
         echo "$symbols" >> $GITHUB_ENV
         echo '\n' >> $GITHUB_ENV
       shell: bash
